### ISSUE TITLE
[Bug]: Missing type in Graph Query fields for Product entity

### ISSUE THREAD

**Issue by jakeaturner** [medusajs/medusa#10401]
### Package.json file

```JSON
{
  "name": "my-medusa",
  "version": "0.0.1",
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "latest",
    "@medusajs/cli": "latest",
    "@medusajs/framework": "latest",
    "@medusajs/medusa": "latest",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "awilix": "^8.0.1",
    "axios": "^1.7.7",
    "pg": "^8.13.0",
    "stripe": "^17.4.0"
  },
  "devDependencies": {
    "@medusajs/test-utils": "latest",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v20.18.0

### Database and its version

PostgreSQL 16.3

### Operating system name and version

Windows 10

### What happended?

In following [this guide](https://docs.medusajs.com/resources/commerce-modules/product/guides/price), I was attempting to include the "variants.prices.\*" relation in my Graph query. However, it seems that "variants.prices.\*" is not recognized by TypeScript as a valid field/relation. 

After `@ts-ignore`-ing this error, though, this relation does load without issue and I can get the `prices` object on each variant. Potentially a missing declaration in the generated(?) `.medusa\types\remote-query-entry-points.d.ts` types?

I'm still getting used to working with v2 and the more advanced customizations, so apologies if I'm totally off base here.

```
  const { data: products } = await query.graph({
    entity: "product",
    fields: [
      "*",
      "variants.*",
      "variants.prices.*",
    ],
    filters: {
      id: req.params.id,
    },
  });
```

P.S. Medusa is a great framework, very thankful to have it around :)

### Expected behavior

`variants.prices.*` is recognized as a valid field/relation on the "product" entity using Query.

### Actual behavior

```
Type '"variants.prices.*"' is not assignable to type '"length" | "description" | "metadata" | "id" | "title" | "handle" | "subtitle" | "is_giftcard" | "status" | "thumbnail" | "width" | "weight" | "height" | "origin_country" | "hs_code" | ... 469 more ... | "sales_channels_link.sales_channel.is_disabled"'. Did you mean '"variants.price_set.*"'?
```

### Link to reproduction repo

https://github.com/medusajs/medusa

**Comment by thetutlage** [comment]
Hello @jakeaturner 

This is indeed a bug and we will look into it. Thanks for reporting 🙏

**Comment by thetutlage** [comment]
This has been fixed and shouldn't report any type errors. https://github.com/medusajs/medusa/pull/10657

**Comment by meenal9** [comment]
@jakeaturner @thetutlage , I am still getting this same issue, I have tried everything and cant get the variants prices for vendor products using "variants.prices.*", Please help how to resolve this?
