### ISSUE TITLE
[CORE-942] [stripe] 3 payment intents created for 2 providers when updating cart totals

### ISSUE THREAD

**Issue by chemicalkosek** [medusajs/medusa#2736]
### Describe the bug

If there are two providers available (ie. stripe and stripe-przelewy24) and the customer is a new email, then if you update the cart totals, we end up with 3 payment intents: 2 with new totals, 1 with initial totals.
This doesn't happen when the customer already existed in stripe before starting the checkout.

### System information

Medusa version (including plugins): 1.6.4, medusa-payment-stripe: 1.1.48

### Steps to reproduce the behavior

1. Have two stripe providers enabled (in example `stripe` and `stripe-przelewy24`)
2. Add one item to cart.
3. Go to checkout
4. Fill in customer email. Important: must be a new stripe customer email. 
5. Create payment sessions on cart
6. See two payment intents in stripe dashboard
7. Add something new to cart (new item or add shipping) 
8. See three payment intents in stripe dashboard. 2 intents with new totals. 1 intent with the initial totals.

### Expected behavior

2 payment intents for 2 providers with correct totals.

### Screenshots

![image](https://user-images.githubusercontent.com/11018707/206152152-75e4a87a-994c-4146-aa21-5d1b548698d8.png)

### Additional context

This PR (which is included in 1.1.48) states that it should be fixed, but that's unfortunately not the case: https://github.com/medusajs/medusa/pull/2603

<sub>[CORE-942](https://linear.app/medusajs/issue/CORE-942/[stripe]-3-payment-intents-created-for-2-providers-when-updating-cart)</sub>

**Comment by olivermrbl** [comment]
Thanks for reporting this one @chemicalkosek. 

@adrien2p Would you be up for digging a bit into this one?

**Comment by adrien2p** [comment]
Yes sure 💪

**Comment by chemicalkosek** [comment]
I have also noticed that sometimes the number of customers in that situation is doubled (same email)
1 payment session = 2 customers
3 payment sessions = 6 customers

**Comment by adrien2p** [comment]
@olivermrbl, in the cart, set payment sessions, if the total > 0 and if there is only one provider and no payment session, then we create a new session. Could it be the issue? So we update one and create a new one? could it be it?

**Comment by olivermrbl** [comment]
@adrien2p This is solved in the latest Stripe version right? As part of #2743

**Comment by chemicalkosek** [comment]
Just tested and looks like it's still happening. Even worse.
I have something in cart.I have 2 initial payment intents created. After adding again something to cart I have now from 8 to 12 payment intents.
2 intents have the new price and there are additional intents created with initial price (!)

![image](https://user-images.githubusercontent.com/11018707/210209413-7512d72f-56b3-4679-896d-981ccecf7f8d.png)

**Comment by olivermrbl** [comment]
Thanks for sharing @chemicalkosek. We'll attend to this one.

**Comment by adrien2p** [comment]
@chemicalkosek can you share us the packages versions you are using please?

**Comment by chemicalkosek** [comment]
```
"medusa-payment-stripe": "^1.1.50",
"@medusajs/medusa": "^1.7.2",
```

**Comment by adrien2p** [comment]
@chemicalkosek I found the issue, I ll release a snapshot that you will be able to test very soon, thanks again for reporting

reference: https://github.com/medusajs/medusa/pull/2921

**Comment by adrien2p** [comment]
<img width="1452" alt="Screenshot 2023-01-02 at 12 55 41" src="https://user-images.githubusercontent.com/25098370/210228021-e5440e64-395f-4a8d-8070-f7ec924aec3e.png">
