### ISSUE TITLE
On draft orders, promo codes cannot be applied, it just loads. 

### ISSUE THREAD

**Issue by magdafiktus** [medusajs/medusa#3332]
### Describe the bug

On draft orders, promo codes cannot be applied, it just loads. 

### System information

"@medusajs/medusa": "1.7.2-snapshot-20221228134959",
"@medusajs/medusa-cli": "^1.3.5",
"medusa-core-utils": "^1.1.36",
"medusa-file-spaces": "1.3.1",
"medusa-fulfillment-manual": "1.1.31",
"medusa-fulfillment-webshipper": "^1.3.3",
"medusa-interfaces": "1.3.3",
"medusa-payment-adyen": "1.1.39",
"medusa-payment-klarna": "1.3.4",
"medusa-payment-manual": "^1.0.19",
"medusa-payment-paypal": "1.2.6",
"medusa-payment-stripe": "1.1.49",
"medusa-plugin-brightpearl": "1.3.2",
"medusa-plugin-contentful": "^1.2.3",
"medusa-plugin-discount-generator": "1.1.19",
"medusa-plugin-ip-lookup": "1.2.1",
"medusa-plugin-meilisearch": "1.0.0",
"medusa-plugin-restock-notification": "2.0.0",
"medusa-plugin-segment": "^1.3.0",
"medusa-plugin-sendgrid": "1.3.3",
"medusa-plugin-sentry": "^1.2.3",
"medusa-plugin-slack-notification": "1.3.4",
"medusa-plugin-wishlist": "1.1.37",
"medusa-test-utils": "1.1.37",
Node -> v16.x
OS -> Ubuntu 18.04
(https://teklafabrics.slack.com/archives/D02Q3RLSUCA/p1674042777633589)
Database -> Postgres

Steps to reproduce the behavior
1. make a draft order
2. try to apply working promo code

### Expected behavior

The discount should kick in

### Screenshots

<img width="1109" alt="Screenshot 2023-02-24 at 14 42 55" src="https://user-images.githubusercontent.com/116171296/221193435-c22abb43-d940-4d13-879f-5fe0075c9c0b.png">

**Comment by olivermrbl** [comment]
Solved in [#905](https://github.com/medusajs/admin/pull/905)

**Comment by gedesurya125** [comment]
Hi,

I am still encountering this issue. In my case, I tried to create a discounted Quote using the Medusa B2B Starter from this link: [Medusa B2B Starter](https://medusajs.com/blog/announcing-b2b-starter/).

I noticed that the quote actually is a draft order as attached code below:
file-name: create-request-for-quote.ts
location: b2b-starter-medusa/backend/src/workflows/quote/workflows/create-request-for-quote.ts

![Image](https://github.com/user-attachments/assets/aa8e0ad8-4221-4316-a9d9-640fe9fd0972)


Steps to Reproduce:
	1.	Create a promotion code in the admin dashboard.
	2.	Add some products to the cart  In the storefront,  then apply the discount code on the cart page.
	3.	Click the “Request Quote” button.
	4.	Open the newly created quote in the admin dashboard – you will notice that the discount field displays ”-” instead of applying the discount.



I have also upgraded Medusa and its dependencies to the latest version, 2.6.1, but the issue still persist. 

My package.json file screenshot attached


![Image](https://github.com/user-attachments/assets/4010e994-a2b3-4998-9729-ea9d0a640d75)

![Image](https://github.com/user-attachments/assets/cf98a13a-8967-4ccc-8364-076a656cb7ec)

![Image](https://github.com/user-attachments/assets/f664c56a-d62e-47e3-93d0-59d95a6e1373)
