### ISSUE TITLE
Bug: payment.webhook_received unable to match payment_provider pp_stripe

### ISSUE THREAD

**Issue by 420coupe** [medusajs/medusa#9494]
### Describe the bug

The endpoint payment.webhook_received is failing to match payment provider with id pp_stripe. Order is still placed and considered successful, payment is captured in stripe however the webhook fails because it doesn't match pp_stripe to any provider. 

### System information

Medusa version (including plugins):``@medusajs/medusa@2.0.0-rc-20241003153304``
Node.js version: ``v21.7.1``
Database: ``Supabase (postgres)``
Operating system: ``Ubuntu 22.04.4``
Browser (if relevant):

### Steps to reproduce the behavior

1. Stand up new medusa backend with latest dev code (RC)
2. create an order
3. order goes through successfully, however stripe has 2 attempts to capture the same payment_intent and payment.webhook_received fails which is file ``packges/modules/payment/src/services/payment-provider``

### Expected behavior

Submit an order and correctly match to payment provider which i believe should be ``pp_stripe_stripe`` instead of ``pp_stripe``

### Screenshots

![image](https://github.com/user-attachments/assets/591fb65a-80e0-4aed-98ab-0a9ba1e43311)
![image](https://github.com/user-attachments/assets/920c06a9-a095-4429-880e-add7f81f45aa)
![image](https://github.com/user-attachments/assets/3eaf2ed5-b6f2-4b86-acb5-53cc4d47a9a2)

### Code snippets
medusa-config.js
```ts
const { loadEnv, defineConfig, Modules } = require("@medusajs/framework/utils");

loadEnv(process.env.NODE_ENV, process.cwd());

module.exports = defineConfig({
  projectConfig: {
    databaseUrl: process.env.DATABASE_URL,
    http: {
      storeCors: process.env.STORE_CORS,
      adminCors: process.env.ADMIN_CORS,
      authCors: process.env.AUTH_CORS,
      jwtSecret: process.env.JWT_SECRET || "supersecret",
      cookieSecret: process.env.COOKIE_SECRET || "supersecret",
    },
  },
admin: {
	backendUrl: process.env.MEDUSA_BACKEND_URL,
	path: process.env.MEDUSA_ADMIN_PATH,
	},
  modules: {
    digitalProductModuleService: {
      resolve: "./modules/digital-product",
    },
    [Modules.FULFILLMENT]: {
      resolve: "@medusajs/medusa/fulfillment",
      options: {
        providers: [
          {
            resolve: "@medusajs/medusa/fulfillment-manual",
            id: "manual",
          },
          {
            resolve: "./modules/digital-product-fulfillment",
            id: "digital",
          },
        ],
      },
    },
    [Modules.NOTIFICATION]: {
      resolve: "@medusajs/medusa/notification",
      options: {
        providers: [
          {
            resolve: "@medusajs/medusa/notification-sendgrid",
            id: "sendgrid",
            options: {
              channels: ["email"],
              api_key: process.env.SENDGRID_API_KEY,
              from: process.env.SENDGRID_FROM,
            },
          },
        ],
      },
    },
    [Modules.PAYMENT]: {
      resolve: "@medusajs/medusa/payment",
      options: {
        providers: [
          {
            resolve: "@medusajs/medusa/payment-stripe",
            id: "stripe",
            options: {
              apiKey: process.env.STRIPE_API_KEY,
              automatic_payment_methods: true,
              capture: true,
            },
          },
        ],
      },
    },
    [Modules.FILE]: {
      resolve: "@medusajs/medusa/file",
      options: {
        providers: [
          {
            resolve: "@medusajs/medusa/file-s3",
            id: "s3",
            options: {
              file_url: process.env.SUPABASE_S3_FILE_URL,
              access_key_id: process.env.SUPABASE_S3_ACCESS_KEY,
              secret_access_key: process.env.SUPABASE_S3_SECRET_KEY,
              region: process.env.SUPABASE_S3_REGION,
              bucket: process.env.SUPABASE_S3_BUCKET,
              endpoint: process.env.SUPABASE_S3_ENDPOINT,
              prefix: process.env.SUPABASE_S3_PREFIX,
              additional_client_config: {
                forcePathStyle: true,
              },
            },
          },
        ],
      },
    },
  },
});

```

**Comment by olivermrbl** [comment]
@420coupe can you let me know what the provider ID of the payment is? As you say, this should be `pp_stripe_stripe` since you are using the standard credit card method.

![CleanShot 2024-10-08 at 09 33 52](https://github.com/user-attachments/assets/334120fc-6447-42eb-9502-cf2cf4153155)

**Comment by 420coupe** [comment]
> @420coupe can you let me know what the provider ID of the payment is? As you say, this should be `pp_stripe_stripe` since you are using the standard credit card method.
> 
> ![CleanShot 2024-10-08 at 09 33 52](https://private-user-images.githubusercontent.com/59018053/374455383-334120fc-6447-42eb-9502-cf2cf4153155.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MDc3OTYsIm5iZiI6MTcyODQwNzQ5NiwicGF0aCI6Ii81OTAxODA1My8zNzQ0NTUzODMtMzM0MTIwZmMtNjQ0Ny00MmViLTk1MDItY2YyY2Y0MTUzMTU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDE3MTEzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmYTVjM2E3NjA3YmUyNWI1ZWFmNDY3NzBmNzRhZTQ5M2VmYjRkMTA4NDI2OWE3NTkyNjJiZDJjZGZjNWQ3MTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.u7ER5vQD4k1j3Sv_m8DhKA7lFTuQ2m4tygVlbZ4eh2w)

provider id in the db is ``pp_stripe_stripe``
![image](https://github.com/user-attachments/assets/5ed7487d-998b-4e88-bce2-b1fd7143cef5)


I have also tried paymentElement vs CardElement and still getting the same results, two capture attempts and error matching coming back to the payment.webhook_received

**Comment by 420coupe** [comment]
also something else i just noticed while digging in the db, status is never updated from ``authorized`` to ``capture``  in `payment_collections` nor `payment_sessions`

to add on this ``payment_session.data.status`` is never updated either, not sure if this is handled by the stripe_webhook return since i've never got it working.

**Comment by renequez** [comment]
@420coupe did you manage to figure out what's causing this? Or a workaround? I have the same problem and the order remains with an outstanding amount, even if the payment shows as captured.

**Comment by 420coupe** [comment]
> @420coupe did you manage to figure out what's causing this? Or a workaround? I have the same problem and the order remains with an outstanding amount, even if the payment shows as captured.

I did not, figured core team was on it from oliver responding.

**Comment by RATIU5** [comment]
I've targeted the problem, going to try some things and create a PR if successful.

**Comment by RATIU5** [comment]
The issue lies in [this line of code](https://github.com/medusajs/medusa/blob/6496789c65a032b7c83f5b2a9c285c2620d4288a/packages/modules/payment/src/services/payment-module.ts#L855) (I think). For me, I changed it to this:

```ts
const providerId = `pp_${eventData.provider}_${eventData.provider.split("_")[0]}`;
```
And it works great. I forcefully changed the `node_module` file to the above line to fix, so it is a temporary fix. I am unsure if this breaks other code as I have not been able to test it fully yet.

**Comment by MiguelFranken** [comment]
I think this line might be correct as payment provider's provider_id is defined as `pp_{identifier}_{id}`, where `{id}` is the provider's `id` property in the `medusa-config.ts`.
See https://github.com/medusajs/medusa/blob/92bbd7953bf3413c649ad605960eac38dac6ee34/packages/core/utils/src/payment/abstract-payment-provider.ts#L113

I had similar issues today and I found out that you need to use the webhook AP Iroute `localhost:9000/hooks/payment/stripe_stripe` when you use the default "card" stripe provder service.

**Comment by renequez** [comment]
I can confirm changing the webhook url to `{medusaUrl}/hooks/payment/stripe_stripe` works fine 👌

**Comment by 420coupe** [comment]
> I can confirm changing the webhook url to `{medusaUrl}/hooks/payment/stripe_stripe` works fine 👌

so even with changing webhook to this, still get this error below when it tries to process. 

```log
info:    Processing payment.webhook_received which has 1 subscribers
error:   An error occurred while processing payment.webhook_received: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
http:    POST /hooks/payment/stripe_stripe ← - (200) - 4.817 ms 
```


edit: also there's still two capture attempts i can see in the stripe logs, still want to know what's causing this to try to collect twice on the payment_intent

**Comment by 420coupe** [comment]
Bump to get a resolution for this.

**Comment by 420coupe** [comment]
anyone?

**Comment by 420coupe** [comment]
bump to get a resolution for this

**Comment by sradevski** [comment]
@420coupe can you maybe open a new ticket with the exact issue you are seeing, and maybe a reproduction? I believe this issue is resolved already, so it's better to move the conversation in a new issue for better visibility. Thanks!

**Comment by bayraak** [comment]
I'm getting the same issue, I'm unable to create a `payment_session` due to this error:

```
 Unable to retrieve the payment provider with id: pp_stripe_stripe
      Please make sure that the provider is registered in the container and it is configured correctly in your project configuration file.
```

Storefront
```js
    "@medusajs/icons": "2.1.3",
    "@medusajs/js-sdk": "2.1.3",
    "@medusajs/types": "2.1.3",
    "@medusajs/ui": "4.0.2",
```

Backend/Admin:
```
    "@medusajs/admin-sdk": "2.1.3",
    "@medusajs/cli": "2.1.3",
    "@medusajs/framework": "2.1.3",
    "@medusajs/js-sdk": "2.1.3",
    "@medusajs/medusa": "2.1.3",
```

Entity in db with proper `pp_stripe_stripe` pk:

<img width="892" alt="image" src="https://github.com/user-attachments/assets/8c73604a-3a0d-4690-b7c3-c52a3f2627e7" />

**Comment by 420coupe** [comment]
> @420coupe can you maybe open a new ticket with the exact issue you are seeing, and maybe a reproduction? I believe this issue is resolved already, so it's better to move the conversation in a new issue for better visibility. Thanks!


Opened another issue below. Still facing an issue with webhook which is not is now providing an issue during checkout utilizing the paymentElement implemented following the guide. 

https://github.com/medusajs/medusa/issues/10949
